package Movies::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config( schema_class => 'Movies::Schema' );

=head1 NAME

Movies::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Movies>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Movies::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.26

=head1 AUTHOR

A clever guy

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
